displayName=B0aty HCIM Guide v3
author=Previn
description=B0aty HCIM Guide but like questhelper
tags=ironman,hcim,guide,quest,skilling,route,b0aty,boaty,checklist
plugins=com.b0atyguide.B0atyGuidePlugin
version=1.3.0
build=standard
